Random VC Funds/Accelerators
*   [500 Startups](http://500.co) and [500 Startups Distrofund](http://500.co/distrofund)
*   [Expa](http://expa.com) 
*   [Google Capital](http://www.googlecapital.com)
*   [Jason Calcanis Syndicate](https://angel.co/jason/syndicate), [Launch Incubator](https://medium.com/@jason/are-you-ready-to-change-your-life-forever-d40d93e964ab), and [Office Hours](https://launch.submittable.com/submit/37635)
*   [Scholas Labs (Launched by Pope Francis)](http://scholaslabs.org)
*   [Silicon Valley Bank](http://www.svb.com) 
*   [Techstars](http://www.techstars.com)
*   [Union Square Ventures](https://www.usv.com)
*   [YCombinator](http://ycombinator.com)
